spring.application.name=Product-Management

# XML
mybatis-plus.mapper-locations=classpath:mapper/*.xml

# XML ? resultType
mybatis-plus.type-aliases-package=com.example.productmanagement.entity, com.example.productmanagement.vo

mybatis-plus.configuration.map-underscore-to-camel-case=true

# SQL
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/nautical_mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456

# ???????? username ? password ????? MySQL ???????
server.port=8083